### ISSUE TITLE
api yaml links lead to about:blank

### ISSUE THREAD

**Issue by eric-jahn** [hmis-api/api-source#1]
![gh](https://user-images.githubusercontent.com/4115079/41830819-3ab29622-7811-11e8-81de-cd9621b309ab.png)

**Comment by eric-jahn** [comment]
Remove API YAML link and replace with the repo link for that API.

**Comment by eric-jahn** [comment]
I think this would be a good pattern to emulate:
![opencriswagger](https://user-images.githubusercontent.com/4115079/90268966-d95b0a80-de25-11ea-859d-60b3b26594be.png)
Keep the link, but make it point to the api source in the repo.  Add a link to the entire repo, and a license link to the repo.  Contact goes to our website.

**Comment by logicsandeep** [comment]
This issue is closed
<img width="1386" alt="Screen Shot 2020-12-06 at 5 32 18 PM" src="https://user-images.githubusercontent.com/4108057/101295029-06726500-37e9-11eb-8bba-435503e6c6ac.png">
.
