### ISSUE TITLE
global household label -> generic household in swagger upper right picklist menu

### ISSUE THREAD

**Issue by eric-jahn** [hmis-api/api-source#7]
![Screenshot from 2019-12-19 15-32-31](https://user-images.githubusercontent.com/4115079/71207965-0561c400-2276-11ea-977b-44f137801745.png)

**Comment by logicsandeep** [comment]
I've change the dropdown from Global household to Generic household.
<img width="1434" alt="Screen Shot 2019-12-24 at 7 18 59 AM" src="https://user-images.githubusercontent.com/4108057/71416470-c9d04c80-261d-11ea-9801-14eef32bb8ef.png">
