### ISSUE TITLE
add HMIS in front of Version Specific APIs

### ISSUE THREAD

**Issue by eric-jahn** [hmis-api/api-source#8]
So in the Swagger menu, where it says "2020 Apis", we would change that to "HMIS 2020 API" and the same for the other years,  ![addhmis](https://user-images.githubusercontent.com/4115079/78382747-525b7300-75a5-11ea-8530-5041d74fc3b2.png)
While we are at it, could we change all mentions of "Api" or "Apis" in that same menu, to "API" or "APIs"?

**Comment by eric-jahn** [comment]
https://github.com/hmis-interop/logical-model/wiki/HMIS-Data-Standard-Versions
4/3, we decided to add HMIS version number, year

**Comment by logicsandeep** [comment]
This issue is closed.
https://github.com/hmis-api/api-source/compare/06bd60ee128b...bf290f5d13dc
